services:

  ds:
    image: ros:humble-ros-core
    network_mode: host
    ipc: host
    command: >
      fast-discovery-server 
      --server-id 0
      --ip-address 127.0.0.1
      --port 1234

  talker:
    image: husarion/ros2-demo-nodes:humble
    network_mode: host
    ipc: host
    environment:
      - ROS_DISCOVERY_SERVER=127.0.0.1:1234
    command: ros2 run demo_nodes_cpp talker

  listener:
    image: husarion/ros2-demo-nodes:humble
    network_mode: host
    ipc: host
    environment:
      - ROS_DISCOVERY_SERVER=127.0.0.1:1234
    command: ros2 run demo_nodes_cpp listener